### ISSUE TITLE
Is there an easy way to drop the default styles?

### ISSUE THREAD

**Issue by Janekk** [rackt/react-tabs#24]
making it configurable would be just fine. Thanks.

**Comment by mzabriskie** [comment]
Is it not possible to override with your own stylesheet?

**Comment by Janekk** [comment]
Yes it is but it seems that now you have to first override/reset multiple default styles on a few levels before you apply your own styles. So what I was thinking about is to add a boolean prop which would control that. Do you think it's possible?

**Comment by mzabriskie** [comment]
Definitely possible. Let me give it some thought.

**Comment by Janekk** [comment]
OK thank you. I've already checked once how styles are being generated and (as far as I remember) it was a single call that bundles them into the page

**Comment by Janekk** [comment]
I've already implemented this feat on my fork. Would like to use it as my dependency for now. How do I run building dist files for `react-tabs`?

**Comment by michaelzoidl** [comment]
Any news? :) Saw the open PR. 
All i want is somewhere a boolean where i can deactivate the default styling... 
Otherwise i've to make a fork where i simply remove the default-stylings :(

**Comment by Janekk** [comment]
PR #25

**Comment by tenorok** [comment]
:+1:
