### ISSUE TITLE
Warning with React 0.14.0

### ISSUE THREAD

**Issue by yapcheahshen** [rackt/react-tabs#41]
Warning: cloneWithProps(...) is deprecated. Please use React.cloneElement instead.
Warning: Tab.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead.

**Comment by danez** [comment]
For the second warning there is already a PR #30

**Comment by mzabriskie** [comment]
These warnings will be fixed with the next release.
